## Sudoku Solver project

In [82]:
# This is a first, so you still have to imput the numbers in the grid.

In [83]:
import numpy as np

In [134]:
grid = [[6,5,0,0,7,9,3,0,0],
        [0,0,2,0,0,0,0,0,6],
        [0,0,9,0,0,5,0,0,0],
        [0,0,0,0,2,0,0,8,0],
        [0,9,0,0,0,0,0,0,0],
        [5,3,0,0,0,8,0,0,4],
        [0,0,0,1,0,0,7,0,0],
        [0,0,6,0,0,0,0,0,0],
        [4,8,0,0,0,2,0,0,3]]

In [112]:
print(grid)

[[0, 1, 0, 0, 0, 0, 7, 0, 0], [7, 0, 3, 0, 0, 0, 0, 0, 9], [9, 0, 0, 3, 7, 4, 6, 0, 0], [0, 0, 0, 4, 9, 0, 0, 8, 2], [0, 9, 6, 2, 0, 8, 0, 0, 0], [2, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0], [8, 3, 0, 0, 4, 9, 5, 0, 7], [0, 4, 9, 0, 0, 0, 0, 0, 3]]


In [116]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [125]:
def possible(y,x,n) :
    global grid
    for i in range(0,9) :
        if grid [y][i] == n :
            return False
    for i in range(0,9):
        if grid [i][x] == n :
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3) :
        for j in range(0,3) :
            if grid[y0+i][x0+j] == n :
                return False
    return True            

In [88]:
# possible(x,y,n) means "x" is the location in the matrix from left to right of the number we want to check from 0 to 8
# "y" is location from the top to the bottom and "n" is the number we want to check. 
# If returns True, the number can be added to the field.

In [89]:
possible(0,0,6)

True

In [90]:
possible(6,3,1)

False

In [91]:
possible(4,3,9)

False

In [135]:
def solve() :
    global grid
    for y in range(9) :
        for x in range(9) :
            if grid[y][x] == 0 :
                for n in range(1,10) :
                    if possible(y,x,n) :
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    input('Done')

In [ ]:
solve()

[[6 5 1 8 7 9 3 4 2]
 [8 7 2 4 3 1 5 9 6]
 [3 4 9 2 6 5 8 7 1]
 [1 6 4 3 2 7 9 8 5]
 [2 9 8 6 5 4 1 3 7]
 [5 3 7 9 1 8 2 6 4]
 [9 2 3 1 4 6 7 5 8]
 [7 1 6 5 8 3 4 2 9]
 [4 8 5 7 9 2 6 1 3]]
